# Generated by Django 5.2.15 on 2026-06-05 11:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('minimum_cgpa', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('package_lpa', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('application_deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='jobs_jobpos_title_afd3ed_idx'), models.Index(fields=['application_deadline'], name='jobs_jobpos_applica_179f5a_idx'), models.Index(fields=['minimum_cgpa'], name='jobs_jobpos_minimum_5c050f_idx'), models.Index(fields=['package_lpa'], name='jobs_jobpos_package_6c5384_idx'), models.Index(fields=['company', 'created_at'], name='jobs_jobpos_company_9565a1_idx')],
            },
        ),
    ]
