# Generated by Django 5.2.15 on 2026-06-05 11:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('college_name', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=100)),
                ('graduation_year', models.PositiveIntegerField()),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('phone_number', models.CharField(max_length=15)),
                ('skills', models.TextField(blank=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/%Y/%m/')),
                ('profile_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['college_name'], name='students_st_college_701885_idx'), models.Index(fields=['branch'], name='students_st_branch_a37db8_idx'), models.Index(fields=['graduation_year'], name='students_st_graduat_9fdd53_idx'), models.Index(fields=['cgpa'], name='students_st_cgpa_ae4fc8_idx')],
            },
        ),
    ]
