# Generated by Django 5.2.15 on 2026-06-05 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(db_index=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'RECRUITER'}, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company_name'], name='companies_c_company_14f39a_idx'), models.Index(fields=['location'], name='companies_c_locatio_ec810c_idx'), models.Index(fields=['created_by', 'created_at'], name='companies_c_created_12e662_idx')],
            },
        ),
    ]
